export const INDUSTRIES = [
  { value: 'restaurant', label: '餐飲' },
  { value: 'hospitality', label: '旅遊住宿' },
  { value: 'retail', label: '零售電商' },
  { value: 'technology', label: '科技' },
  { value: 'healthcare', label: '醫療保健' },
  { value: 'traditional_medicine', label: '整復推拿' },
  { value: 'beauty_salon', label: '美容美髮' },
  { value: 'auto_care', label: '汽車美容保養' },
  { value: 'fitness', label: '健身運動' },
  { value: 'education', label: '教育補習' },
  { value: 'finance', label: '金融保險' },
  { value: 'real_estate', label: '不動產' },
  { value: 'professional_services', label: '專業服務' },
  { value: 'pet', label: '寵物服務' },
  { value: 'parenting', label: '親子育兒' },
  { value: 'home_services', label: '居家服務' },
  { value: 'cafe', label: '咖啡茶飲' },
  { value: 'manufacturing', label: '製造業' },
  { value: 'media', label: '媒體' },
  { value: 'nonprofit', label: '非營利' },
  { value: 'local_life', label: '在地生活' },
  { value: 'other', label: '其他' },
] as const;

export type IndustryValue = (typeof INDUSTRIES)[number]['value'];
