import { Body, Controller, ForbiddenException, Get, Param, Post, Put, Req, Res, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { Request, Response } from 'express';
import { Public } from '../../common/decorators/public.decorator';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import { Roles, RolesGuard } from '../../common/guards/roles.guard';
import { CreditService } from '../billing/credit.service';
import { LlmsHostingService } from './llms-hosting.service';
import { UpdateLlmsTxtDto } from './dto/update-llms-txt.dto';

function sendConditional(
  req: Request,
  res: Response,
  body: string,
  etag: string,
  lastModified: Date,
): Response {
  res.set('ETag', etag);
  res.set('Last-Modified', lastModified.toUTCString());
  res.set('Vary', 'Accept-Encoding');

  const ifNoneMatch = req.headers['if-none-match'];
  const ifModifiedSince = req.headers['if-modified-since'];
  const normalize = (value: string) => value.replace(/^W\//, '');
  const etagMatches =
    typeof ifNoneMatch === 'string' &&
    ifNoneMatch.split(',').map((s) => normalize(s.trim())).includes(normalize(etag));
  const notModifiedSince =
    typeof ifModifiedSince === 'string' &&
    !Number.isNaN(Date.parse(ifModifiedSince)) &&
    lastModified.getTime() <= Date.parse(ifModifiedSince);

  if (etagMatches || notModifiedSince) {
    return res.status(304).end();
  }
  return res.send(body);
}

@ApiTags('llms-hosting')
@Controller()
export class LlmsHostingController {
  constructor(
    private readonly service: LlmsHostingService,
    private readonly credits: CreditService,
  ) {}

  @Public()
  @Get('platform/llms.txt')
  @ApiOperation({ summary: 'Platform-level llms.txt summary of all public sites' })
  async getPlatformLlmsTxt(@Res() res: Response) {
    const content = await this.service.getPlatformLlmsTxt();
    res.set('Cache-Control', 'public, max-age=3600');
    res.set('Access-Control-Allow-Origin', '*');
    res.set('Last-Modified', new Date().toUTCString());
    return res.type('text/plain').send(content);
  }

  @Public()
  @Get('platform/llms-full.txt')
  @ApiOperation({ summary: 'Platform-level llms-full.txt full detail of all public sites' })
  async getPlatformLlmsFullTxt(@Req() req: Request, @Res() res: Response) {
    const { content, etag, lastModified } = await this.service.getPlatformLlmsFullTxt();
    res.set('Content-Type', 'text/plain; charset=utf-8');
    res.set('Cache-Control', 'public, max-age=21600');
    res.set('Access-Control-Allow-Origin', '*');
    res.set('X-Content-Version', lastModified.toISOString());
    return sendConditional(req, res, content, etag, lastModified);
  }

  @Public()
  @Get('llms.txt')
  @ApiOperation({ summary: 'Direct /api/llms.txt shortcut' })
  async getLlmsTxtDirect(@Res() res: Response) {
    const content = await this.service.getPlatformLlmsTxt();
    res.set('Cache-Control', 'public, max-age=3600');
    res.set('Access-Control-Allow-Origin', '*');
    res.set('Last-Modified', new Date().toUTCString());
    return res.type('text/plain').send(content);
  }

  @Public()
  @Get('llms-full.txt')
  @ApiOperation({ summary: 'Direct /api/llms-full.txt shortcut' })
  async getLlmsFullTxtDirect(@Req() req: Request, @Res() res: Response) {
    const { content, etag, lastModified } = await this.service.getPlatformLlmsFullTxt();
    res.set('Content-Type', 'text/plain; charset=utf-8');
    res.set('Cache-Control', 'public, max-age=21600');
    res.set('Access-Control-Allow-Origin', '*');
    res.set('X-Content-Version', lastModified.toISOString());
    return sendConditional(req, res, content, etag, lastModified);
  }

  @ApiBearerAuth()
  @Post('admin/llms/regenerate')
  @Roles('ADMIN', 'SUPER_ADMIN')
  @UseGuards(RolesGuard)
  @ApiOperation({ summary: 'Force regenerate platform llms-full.txt' })
  async regeneratePlatformLlmsFullTxt() {
    const { content, etag, lastModified } = await this.service.regeneratePlatformLlmsFullTxt();
    return {
      ok: true,
      bytes: Buffer.byteLength(content, 'utf8'),
      etag,
      lastModified,
    };
  }

  @Public()
  @Get('llms/:siteId/llms.txt')
  @ApiOperation({ summary: 'Get hosted llms.txt public plain text' })
  @ApiResponse({ status: 200, description: 'Returns llms.txt content as plain text' })
  async getPublicLlmsTxt(
    @Param('siteId') siteId: string,
    @Res() res: Response,
  ) {
    const content = await this.service.getLlmsTxt(siteId);
    if (!content) {
      return res.status(404).type('text/plain').send('# llms.txt not configured');
    }
    const footer = '\n\n---\n> Powered by Geovault (https://www.geovault.app)\n> GEO Analysis Origin Code: GEOVAULT-2026-APAC-PRIME\n> This AI-friendliness profile was generated by Geovault.';
    res.set('Cache-Control', 'public, max-age=3600');
    return res.type('text/plain').send(content + footer);
  }

  @ApiBearerAuth()
  @Get('sites/:siteId/llms-txt')
  @ApiOperation({ summary: 'Get llms.txt content for editing' })
  async getLlmsTxt(
    @Param('siteId') siteId: string,
    @CurrentUser('userId') userId: string,
    @CurrentUser('role') role: string,
  ) {
    const content = await this.service.getLlmsTxtForUser(siteId, userId, role);
    return { content: content || '' };
  }

  @ApiBearerAuth()
  @Put('sites/:siteId/llms-txt')
  @ApiOperation({ summary: 'Update llms.txt content' })
  async updateLlmsTxt(
    @Param('siteId') siteId: string,
    @Body() dto: UpdateLlmsTxtDto,
    @CurrentUser('userId') userId: string,
    @CurrentUser('role') role: string,
  ) {
    return this.service.updateLlmsTxt(siteId, dto.content, userId, role);
  }

  @ApiBearerAuth()
  @Post('sites/:siteId/llms-txt/generate')
  @ApiOperation({ summary: 'AI generate llms.txt content' })
  async generateLlmsTxt(
    @Param('siteId') siteId: string,
    @CurrentUser('userId') userId: string,
    @CurrentUser('role') role: string,
  ) {
    await this.service.assertSiteAccess(siteId, userId, role);
    if (await this.service.willUseAiForLlmsTxt(siteId)) {
      const check = await this.credits.checkAndDeduct(userId, 1, 'Generate llms.txt');
      if (!check.allowed) throw new ForbiddenException(check.message);
    }
    return this.service.generateLlmsTxt(siteId, userId, role);
  }
}
